FROM ubuntu:16.04

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev curl iputils-ping dnsutils git\
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

WORKDIR /app
ENTRYPOINT ["python"]
CMD ["main.py"]
